-- Generated by tools/wide-schema for MySQL. DO NOT EDIT.
-- Regenerate from the repository root with: go run ./tools/wide-schema
--
-- This is schema only: it deliberately contains no rows or foreign keys. Its
-- size is what makes catalog navigation real rather than a one-object happy path,
-- but the fixture must still be safe for every test that shares these databases.
--
-- The 256-column archive table is deliberately in the second schema each engine
-- exposes: harbor follows atelier in PostgreSQL, and ledger follows MySQL's
-- testbed database. A resolver that reads only the first schema would
-- otherwise find enough ordinary tables to look healthy while never reaching the
-- wide-table path this fixture is here to exercise.
--
-- The shapes are consequently not symmetric. PostgreSQL schemas are namespaces
-- inside testbed, while a MySQL schema is a database; more than one schema there
-- must be testbed and ledger, not two names nested in testbed. Keeping that
-- distinction visible prevents a cross-engine abstraction from hiding it.
--
-- Three tables are named for an index or key property rather than thematically:
-- multi_column_index_probe, multi_index_probe and wide_composite_key_probe. Each
-- exists so that a reader of the catalog can be graded on one thing -- key order
-- in a multi-column index, several indexes on one table including both spellings
-- of uniqueness, and a several-hundred-column table under a composite key. They
-- are in every schema and database here, unlike archive's width, because a test
-- that names one of them should not also have to know which schema it landed in.
--
-- PostgreSQL's init connection is its image superuser, so SET ROLE cerberus below
-- is load-bearing rather than cosmetic. Without it that superuser owns the named
-- schemas and their tables, while the test login merely connects and cannot read
-- the fixture; creating them as cerberus makes its ownership the permission grant.

USE testbed;

CREATE TABLE archive (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_archive_title ON archive (title);

CREATE TABLE beacon (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_beacon_title ON beacon (title);

CREATE TABLE canvas (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_canvas_title ON canvas (title);

CREATE TABLE docket (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_docket_title ON docket (title);

CREATE TABLE ember (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_ember_title ON ember (title);

CREATE TABLE folio (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_folio_title ON folio (title);

CREATE TABLE grotto (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_grotto_title ON grotto (title);

CREATE TABLE harvest (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_harvest_title ON harvest (title);

CREATE TABLE island (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_island_title ON island (title);

CREATE TABLE juncture (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_juncture_title ON juncture (title);

CREATE TABLE keystone (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_keystone_title ON keystone (title);

CREATE TABLE lantern (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_lantern_title ON lantern (title);

CREATE TABLE meadow (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_meadow_title ON meadow (title);

CREATE TABLE nexus (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_nexus_title ON nexus (title);

CREATE TABLE orchard (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_orchard_title ON orchard (title);

CREATE TABLE pavilion (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_pavilion_title ON pavilion (title);

CREATE TABLE quarry (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_quarry_title ON quarry (title);

CREATE TABLE rivulet (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_rivulet_title ON rivulet (title);

CREATE TABLE signal_post (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_signal_post_title ON signal_post (title);

CREATE TABLE terrace (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_terrace_title ON terrace (title);

CREATE TABLE uplink (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_uplink_title ON uplink (title);

CREATE TABLE vessel (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_vessel_title ON vessel (title);

CREATE TABLE waypoint (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_waypoint_title ON waypoint (title);

CREATE TABLE yearbook (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_yearbook_title ON yearbook (title);

CREATE TABLE zenith (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_zenith_title ON zenith (title);

CREATE TABLE alcove (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_alcove_title ON alcove (title);

CREATE TABLE bastion (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_bastion_title ON bastion (title);

CREATE TABLE cairn (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_cairn_title ON cairn (title);

CREATE TABLE drift (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_drift_title ON drift (title);

CREATE TABLE estuary (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_estuary_title ON estuary (title);

CREATE TABLE foundry (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_foundry_title ON foundry (title);

CREATE TABLE gallery (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_gallery_title ON gallery (title);

CREATE TABLE horizon (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_horizon_title ON horizon (title);

CREATE TABLE inlet (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_inlet_title ON inlet (title);

CREATE TABLE journey (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_journey_title ON journey (title);

CREATE TABLE kiosk (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_kiosk_title ON kiosk (title);

CREATE TABLE lookout (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_lookout_title ON lookout (title);

CREATE TABLE mosaic (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_mosaic_title ON mosaic (title);

CREATE TABLE notion (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_notion_title ON notion (title);

CREATE TABLE outpost (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_outpost_title ON outpost (title);

CREATE TABLE pier (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_pier_title ON pier (title);

CREATE TABLE quiver (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_quiver_title ON quiver (title);

CREATE TABLE roost (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_roost_title ON roost (title);

CREATE TABLE summit (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_summit_title ON summit (title);

CREATE TABLE thicket (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_thicket_title ON thicket (title);

CREATE TABLE union_hall (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_union_hall_title ON union_hall (title);

CREATE TABLE veranda (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_veranda_title ON veranda (title);

CREATE TABLE workshop (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_workshop_title ON workshop (title);

CREATE TABLE yonder (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_yonder_title ON yonder (title);

CREATE TABLE zephyr (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_zephyr_title ON zephyr (title);

CREATE TABLE multi_column_index_probe (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_multi_column_index_probe_recorded_at_title_amount ON multi_column_index_probe (recorded_at, title, amount);

CREATE TABLE multi_index_probe (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  serial_code VARCHAR(40) NOT NULL,
  batch_code VARCHAR(40) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_multi_index_probe_batch_code UNIQUE (batch_code)
);
CREATE INDEX ix_multi_index_probe_title ON multi_index_probe (title);
CREATE UNIQUE INDEX ux_multi_index_probe_serial_code ON multi_index_probe (serial_code);

CREATE TABLE wide_composite_key_probe (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  gauge_001 INTEGER,
  gauge_002 BIGINT,
  gauge_003 DECIMAL(12, 2) NOT NULL,
  gauge_004 TEXT,
  gauge_005 INTEGER,
  gauge_006 BIGINT NOT NULL,
  gauge_007 DECIMAL(12, 2),
  gauge_008 TEXT,
  gauge_009 INTEGER NOT NULL,
  gauge_010 BIGINT,
  gauge_011 DECIMAL(12, 2),
  gauge_012 TEXT NOT NULL,
  gauge_013 INTEGER,
  gauge_014 BIGINT,
  gauge_015 DECIMAL(12, 2) NOT NULL,
  gauge_016 TEXT,
  gauge_017 INTEGER,
  gauge_018 BIGINT NOT NULL,
  gauge_019 DECIMAL(12, 2),
  gauge_020 TEXT,
  gauge_021 INTEGER NOT NULL,
  gauge_022 BIGINT,
  gauge_023 DECIMAL(12, 2),
  gauge_024 TEXT NOT NULL,
  gauge_025 INTEGER,
  gauge_026 BIGINT,
  gauge_027 DECIMAL(12, 2) NOT NULL,
  gauge_028 TEXT,
  gauge_029 INTEGER,
  gauge_030 BIGINT NOT NULL,
  gauge_031 DECIMAL(12, 2),
  gauge_032 TEXT,
  gauge_033 INTEGER NOT NULL,
  gauge_034 BIGINT,
  gauge_035 DECIMAL(12, 2),
  gauge_036 TEXT NOT NULL,
  gauge_037 INTEGER,
  gauge_038 BIGINT,
  gauge_039 DECIMAL(12, 2) NOT NULL,
  gauge_040 TEXT,
  gauge_041 INTEGER,
  gauge_042 BIGINT NOT NULL,
  gauge_043 DECIMAL(12, 2),
  gauge_044 TEXT,
  gauge_045 INTEGER NOT NULL,
  gauge_046 BIGINT,
  gauge_047 DECIMAL(12, 2),
  gauge_048 TEXT NOT NULL,
  gauge_049 INTEGER,
  gauge_050 BIGINT,
  gauge_051 DECIMAL(12, 2) NOT NULL,
  gauge_052 TEXT,
  gauge_053 INTEGER,
  gauge_054 BIGINT NOT NULL,
  gauge_055 DECIMAL(12, 2),
  gauge_056 TEXT,
  gauge_057 INTEGER NOT NULL,
  gauge_058 BIGINT,
  gauge_059 DECIMAL(12, 2),
  gauge_060 TEXT NOT NULL,
  gauge_061 INTEGER,
  gauge_062 BIGINT,
  gauge_063 DECIMAL(12, 2) NOT NULL,
  gauge_064 TEXT,
  gauge_065 INTEGER,
  gauge_066 BIGINT NOT NULL,
  gauge_067 DECIMAL(12, 2),
  gauge_068 TEXT,
  gauge_069 INTEGER NOT NULL,
  gauge_070 BIGINT,
  gauge_071 DECIMAL(12, 2),
  gauge_072 TEXT NOT NULL,
  gauge_073 INTEGER,
  gauge_074 BIGINT,
  gauge_075 DECIMAL(12, 2) NOT NULL,
  gauge_076 TEXT,
  gauge_077 INTEGER,
  gauge_078 BIGINT NOT NULL,
  gauge_079 DECIMAL(12, 2),
  gauge_080 TEXT,
  gauge_081 INTEGER NOT NULL,
  gauge_082 BIGINT,
  gauge_083 DECIMAL(12, 2),
  gauge_084 TEXT NOT NULL,
  gauge_085 INTEGER,
  gauge_086 BIGINT,
  gauge_087 DECIMAL(12, 2) NOT NULL,
  gauge_088 TEXT,
  gauge_089 INTEGER,
  gauge_090 BIGINT NOT NULL,
  gauge_091 DECIMAL(12, 2),
  gauge_092 TEXT,
  gauge_093 INTEGER NOT NULL,
  gauge_094 BIGINT,
  gauge_095 DECIMAL(12, 2),
  gauge_096 TEXT NOT NULL,
  gauge_097 INTEGER,
  gauge_098 BIGINT,
  gauge_099 DECIMAL(12, 2) NOT NULL,
  gauge_100 TEXT,
  gauge_101 INTEGER,
  gauge_102 BIGINT NOT NULL,
  gauge_103 DECIMAL(12, 2),
  gauge_104 TEXT,
  gauge_105 INTEGER NOT NULL,
  gauge_106 BIGINT,
  gauge_107 DECIMAL(12, 2),
  gauge_108 TEXT NOT NULL,
  gauge_109 INTEGER,
  gauge_110 BIGINT,
  gauge_111 DECIMAL(12, 2) NOT NULL,
  gauge_112 TEXT,
  gauge_113 INTEGER,
  gauge_114 BIGINT NOT NULL,
  gauge_115 DECIMAL(12, 2),
  gauge_116 TEXT,
  gauge_117 INTEGER NOT NULL,
  gauge_118 BIGINT,
  gauge_119 DECIMAL(12, 2),
  gauge_120 TEXT NOT NULL,
  gauge_121 INTEGER,
  gauge_122 BIGINT,
  gauge_123 DECIMAL(12, 2) NOT NULL,
  gauge_124 TEXT,
  gauge_125 INTEGER,
  gauge_126 BIGINT NOT NULL,
  gauge_127 DECIMAL(12, 2),
  gauge_128 TEXT,
  gauge_129 INTEGER NOT NULL,
  gauge_130 BIGINT,
  gauge_131 DECIMAL(12, 2),
  gauge_132 TEXT NOT NULL,
  gauge_133 INTEGER,
  gauge_134 BIGINT,
  gauge_135 DECIMAL(12, 2) NOT NULL,
  gauge_136 TEXT,
  gauge_137 INTEGER,
  gauge_138 BIGINT NOT NULL,
  gauge_139 DECIMAL(12, 2),
  gauge_140 TEXT,
  gauge_141 INTEGER NOT NULL,
  gauge_142 BIGINT,
  gauge_143 DECIMAL(12, 2),
  gauge_144 TEXT NOT NULL,
  gauge_145 INTEGER,
  gauge_146 BIGINT,
  gauge_147 DECIMAL(12, 2) NOT NULL,
  gauge_148 TEXT,
  gauge_149 INTEGER,
  gauge_150 BIGINT NOT NULL,
  gauge_151 DECIMAL(12, 2),
  gauge_152 TEXT,
  gauge_153 INTEGER NOT NULL,
  gauge_154 BIGINT,
  gauge_155 DECIMAL(12, 2),
  gauge_156 TEXT NOT NULL,
  gauge_157 INTEGER,
  gauge_158 BIGINT,
  gauge_159 DECIMAL(12, 2) NOT NULL,
  gauge_160 TEXT,
  gauge_161 INTEGER,
  gauge_162 BIGINT NOT NULL,
  gauge_163 DECIMAL(12, 2),
  gauge_164 TEXT,
  gauge_165 INTEGER NOT NULL,
  gauge_166 BIGINT,
  gauge_167 DECIMAL(12, 2),
  gauge_168 TEXT NOT NULL,
  gauge_169 INTEGER,
  gauge_170 BIGINT,
  gauge_171 DECIMAL(12, 2) NOT NULL,
  gauge_172 TEXT,
  gauge_173 INTEGER,
  gauge_174 BIGINT NOT NULL,
  gauge_175 DECIMAL(12, 2),
  gauge_176 TEXT,
  gauge_177 INTEGER NOT NULL,
  gauge_178 BIGINT,
  gauge_179 DECIMAL(12, 2),
  gauge_180 TEXT NOT NULL,
  gauge_181 INTEGER,
  gauge_182 BIGINT,
  gauge_183 DECIMAL(12, 2) NOT NULL,
  gauge_184 TEXT,
  gauge_185 INTEGER,
  gauge_186 BIGINT NOT NULL,
  gauge_187 DECIMAL(12, 2),
  gauge_188 TEXT,
  gauge_189 INTEGER NOT NULL,
  gauge_190 BIGINT,
  gauge_191 DECIMAL(12, 2),
  gauge_192 TEXT NOT NULL,
  gauge_193 INTEGER,
  gauge_194 BIGINT,
  gauge_195 DECIMAL(12, 2) NOT NULL,
  gauge_196 TEXT,
  gauge_197 INTEGER,
  gauge_198 BIGINT NOT NULL,
  gauge_199 DECIMAL(12, 2),
  gauge_200 TEXT,
  gauge_201 INTEGER NOT NULL,
  gauge_202 BIGINT,
  gauge_203 DECIMAL(12, 2),
  gauge_204 TEXT NOT NULL,
  gauge_205 INTEGER,
  gauge_206 BIGINT,
  gauge_207 DECIMAL(12, 2) NOT NULL,
  gauge_208 TEXT,
  gauge_209 INTEGER,
  gauge_210 BIGINT NOT NULL,
  gauge_211 DECIMAL(12, 2),
  gauge_212 TEXT,
  gauge_213 INTEGER NOT NULL,
  gauge_214 BIGINT,
  gauge_215 DECIMAL(12, 2),
  gauge_216 TEXT NOT NULL,
  gauge_217 INTEGER,
  gauge_218 BIGINT,
  gauge_219 DECIMAL(12, 2) NOT NULL,
  gauge_220 TEXT,
  gauge_221 INTEGER,
  gauge_222 BIGINT NOT NULL,
  gauge_223 DECIMAL(12, 2),
  gauge_224 TEXT,
  gauge_225 INTEGER NOT NULL,
  gauge_226 BIGINT,
  gauge_227 DECIMAL(12, 2),
  gauge_228 TEXT NOT NULL,
  gauge_229 INTEGER,
  gauge_230 BIGINT,
  gauge_231 DECIMAL(12, 2) NOT NULL,
  gauge_232 TEXT,
  gauge_233 INTEGER,
  gauge_234 BIGINT NOT NULL,
  gauge_235 DECIMAL(12, 2),
  gauge_236 TEXT,
  gauge_237 INTEGER NOT NULL,
  gauge_238 BIGINT,
  gauge_239 DECIMAL(12, 2),
  gauge_240 TEXT NOT NULL,
  gauge_241 INTEGER,
  gauge_242 BIGINT,
  gauge_243 DECIMAL(12, 2) NOT NULL,
  gauge_244 TEXT,
  gauge_245 INTEGER,
  gauge_246 BIGINT NOT NULL,
  gauge_247 DECIMAL(12, 2),
  gauge_248 TEXT,
  gauge_249 INTEGER NOT NULL,
  gauge_250 BIGINT,
  PRIMARY KEY (series_no, area_code)
);
CREATE INDEX ix_wide_composite_key_probe_title ON wide_composite_key_probe (title);

USE ledger;

CREATE TABLE archive (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  measure_001 INTEGER,
  measure_002 BIGINT,
  measure_003 DECIMAL(12, 2) NOT NULL,
  measure_004 TEXT,
  measure_005 INTEGER,
  measure_006 BIGINT NOT NULL,
  measure_007 DECIMAL(12, 2),
  measure_008 TEXT,
  measure_009 INTEGER NOT NULL,
  measure_010 BIGINT,
  measure_011 DECIMAL(12, 2),
  measure_012 TEXT NOT NULL,
  measure_013 INTEGER,
  measure_014 BIGINT,
  measure_015 DECIMAL(12, 2) NOT NULL,
  measure_016 TEXT,
  measure_017 INTEGER,
  measure_018 BIGINT NOT NULL,
  measure_019 DECIMAL(12, 2),
  measure_020 TEXT,
  measure_021 INTEGER NOT NULL,
  measure_022 BIGINT,
  measure_023 DECIMAL(12, 2),
  measure_024 TEXT NOT NULL,
  measure_025 INTEGER,
  measure_026 BIGINT,
  measure_027 DECIMAL(12, 2) NOT NULL,
  measure_028 TEXT,
  measure_029 INTEGER,
  measure_030 BIGINT NOT NULL,
  measure_031 DECIMAL(12, 2),
  measure_032 TEXT,
  measure_033 INTEGER NOT NULL,
  measure_034 BIGINT,
  measure_035 DECIMAL(12, 2),
  measure_036 TEXT NOT NULL,
  measure_037 INTEGER,
  measure_038 BIGINT,
  measure_039 DECIMAL(12, 2) NOT NULL,
  measure_040 TEXT,
  measure_041 INTEGER,
  measure_042 BIGINT NOT NULL,
  measure_043 DECIMAL(12, 2),
  measure_044 TEXT,
  measure_045 INTEGER NOT NULL,
  measure_046 BIGINT,
  measure_047 DECIMAL(12, 2),
  measure_048 TEXT NOT NULL,
  measure_049 INTEGER,
  measure_050 BIGINT,
  measure_051 DECIMAL(12, 2) NOT NULL,
  measure_052 TEXT,
  measure_053 INTEGER,
  measure_054 BIGINT NOT NULL,
  measure_055 DECIMAL(12, 2),
  measure_056 TEXT,
  measure_057 INTEGER NOT NULL,
  measure_058 BIGINT,
  measure_059 DECIMAL(12, 2),
  measure_060 TEXT NOT NULL,
  measure_061 INTEGER,
  measure_062 BIGINT,
  measure_063 DECIMAL(12, 2) NOT NULL,
  measure_064 TEXT,
  measure_065 INTEGER,
  measure_066 BIGINT NOT NULL,
  measure_067 DECIMAL(12, 2),
  measure_068 TEXT,
  measure_069 INTEGER NOT NULL,
  measure_070 BIGINT,
  measure_071 DECIMAL(12, 2),
  measure_072 TEXT NOT NULL,
  measure_073 INTEGER,
  measure_074 BIGINT,
  measure_075 DECIMAL(12, 2) NOT NULL,
  measure_076 TEXT,
  measure_077 INTEGER,
  measure_078 BIGINT NOT NULL,
  measure_079 DECIMAL(12, 2),
  measure_080 TEXT,
  measure_081 INTEGER NOT NULL,
  measure_082 BIGINT,
  measure_083 DECIMAL(12, 2),
  measure_084 TEXT NOT NULL,
  measure_085 INTEGER,
  measure_086 BIGINT,
  measure_087 DECIMAL(12, 2) NOT NULL,
  measure_088 TEXT,
  measure_089 INTEGER,
  measure_090 BIGINT NOT NULL,
  measure_091 DECIMAL(12, 2),
  measure_092 TEXT,
  measure_093 INTEGER NOT NULL,
  measure_094 BIGINT,
  measure_095 DECIMAL(12, 2),
  measure_096 TEXT NOT NULL,
  measure_097 INTEGER,
  measure_098 BIGINT,
  measure_099 DECIMAL(12, 2) NOT NULL,
  measure_100 TEXT,
  measure_101 INTEGER,
  measure_102 BIGINT NOT NULL,
  measure_103 DECIMAL(12, 2),
  measure_104 TEXT,
  measure_105 INTEGER NOT NULL,
  measure_106 BIGINT,
  measure_107 DECIMAL(12, 2),
  measure_108 TEXT NOT NULL,
  measure_109 INTEGER,
  measure_110 BIGINT,
  measure_111 DECIMAL(12, 2) NOT NULL,
  measure_112 TEXT,
  measure_113 INTEGER,
  measure_114 BIGINT NOT NULL,
  measure_115 DECIMAL(12, 2),
  measure_116 TEXT,
  measure_117 INTEGER NOT NULL,
  measure_118 BIGINT,
  measure_119 DECIMAL(12, 2),
  measure_120 TEXT NOT NULL,
  measure_121 INTEGER,
  measure_122 BIGINT,
  measure_123 DECIMAL(12, 2) NOT NULL,
  measure_124 TEXT,
  measure_125 INTEGER,
  measure_126 BIGINT NOT NULL,
  measure_127 DECIMAL(12, 2),
  measure_128 TEXT,
  measure_129 INTEGER NOT NULL,
  measure_130 BIGINT,
  measure_131 DECIMAL(12, 2),
  measure_132 TEXT NOT NULL,
  measure_133 INTEGER,
  measure_134 BIGINT,
  measure_135 DECIMAL(12, 2) NOT NULL,
  measure_136 TEXT,
  measure_137 INTEGER,
  measure_138 BIGINT NOT NULL,
  measure_139 DECIMAL(12, 2),
  measure_140 TEXT,
  measure_141 INTEGER NOT NULL,
  measure_142 BIGINT,
  measure_143 DECIMAL(12, 2),
  measure_144 TEXT NOT NULL,
  measure_145 INTEGER,
  measure_146 BIGINT,
  measure_147 DECIMAL(12, 2) NOT NULL,
  measure_148 TEXT,
  measure_149 INTEGER,
  measure_150 BIGINT NOT NULL,
  measure_151 DECIMAL(12, 2),
  measure_152 TEXT,
  measure_153 INTEGER NOT NULL,
  measure_154 BIGINT,
  measure_155 DECIMAL(12, 2),
  measure_156 TEXT NOT NULL,
  measure_157 INTEGER,
  measure_158 BIGINT,
  measure_159 DECIMAL(12, 2) NOT NULL,
  measure_160 TEXT,
  measure_161 INTEGER,
  measure_162 BIGINT NOT NULL,
  measure_163 DECIMAL(12, 2),
  measure_164 TEXT,
  measure_165 INTEGER NOT NULL,
  measure_166 BIGINT,
  measure_167 DECIMAL(12, 2),
  measure_168 TEXT NOT NULL,
  measure_169 INTEGER,
  measure_170 BIGINT,
  measure_171 DECIMAL(12, 2) NOT NULL,
  measure_172 TEXT,
  measure_173 INTEGER,
  measure_174 BIGINT NOT NULL,
  measure_175 DECIMAL(12, 2),
  measure_176 TEXT,
  measure_177 INTEGER NOT NULL,
  measure_178 BIGINT,
  measure_179 DECIMAL(12, 2),
  measure_180 TEXT NOT NULL,
  measure_181 INTEGER,
  measure_182 BIGINT,
  measure_183 DECIMAL(12, 2) NOT NULL,
  measure_184 TEXT,
  measure_185 INTEGER,
  measure_186 BIGINT NOT NULL,
  measure_187 DECIMAL(12, 2),
  measure_188 TEXT,
  measure_189 INTEGER NOT NULL,
  measure_190 BIGINT,
  measure_191 DECIMAL(12, 2),
  measure_192 TEXT NOT NULL,
  measure_193 INTEGER,
  measure_194 BIGINT,
  measure_195 DECIMAL(12, 2) NOT NULL,
  measure_196 TEXT,
  measure_197 INTEGER,
  measure_198 BIGINT NOT NULL,
  measure_199 DECIMAL(12, 2),
  measure_200 TEXT,
  measure_201 INTEGER NOT NULL,
  measure_202 BIGINT,
  measure_203 DECIMAL(12, 2),
  measure_204 TEXT NOT NULL,
  measure_205 INTEGER,
  measure_206 BIGINT,
  measure_207 DECIMAL(12, 2) NOT NULL,
  measure_208 TEXT,
  measure_209 INTEGER,
  measure_210 BIGINT NOT NULL,
  measure_211 DECIMAL(12, 2),
  measure_212 TEXT,
  measure_213 INTEGER NOT NULL,
  measure_214 BIGINT,
  measure_215 DECIMAL(12, 2),
  measure_216 TEXT NOT NULL,
  measure_217 INTEGER,
  measure_218 BIGINT,
  measure_219 DECIMAL(12, 2) NOT NULL,
  measure_220 TEXT,
  measure_221 INTEGER,
  measure_222 BIGINT NOT NULL,
  measure_223 DECIMAL(12, 2),
  measure_224 TEXT,
  measure_225 INTEGER NOT NULL,
  measure_226 BIGINT,
  measure_227 DECIMAL(12, 2),
  measure_228 TEXT NOT NULL,
  measure_229 INTEGER,
  measure_230 BIGINT,
  measure_231 DECIMAL(12, 2) NOT NULL,
  measure_232 TEXT,
  measure_233 INTEGER,
  measure_234 BIGINT NOT NULL,
  measure_235 DECIMAL(12, 2),
  measure_236 TEXT,
  measure_237 INTEGER NOT NULL,
  measure_238 BIGINT,
  measure_239 DECIMAL(12, 2),
  measure_240 TEXT NOT NULL,
  measure_241 INTEGER,
  measure_242 BIGINT,
  measure_243 DECIMAL(12, 2) NOT NULL,
  measure_244 TEXT,
  measure_245 INTEGER,
  measure_246 BIGINT NOT NULL,
  measure_247 DECIMAL(12, 2),
  measure_248 TEXT,
  measure_249 INTEGER NOT NULL,
  measure_250 BIGINT,
  PRIMARY KEY (id)
);
CREATE INDEX ix_archive_title ON archive (title);

CREATE TABLE beacon (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_beacon_title ON beacon (title);

CREATE TABLE canvas (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_canvas_title ON canvas (title);

CREATE TABLE docket (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_docket_title ON docket (title);

CREATE TABLE ember (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_ember_title ON ember (title);

CREATE TABLE folio (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_folio_title ON folio (title);

CREATE TABLE grotto (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_grotto_title ON grotto (title);

CREATE TABLE harvest (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_harvest_title ON harvest (title);

CREATE TABLE island (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_island_title ON island (title);

CREATE TABLE juncture (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_juncture_title ON juncture (title);

CREATE TABLE keystone (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_keystone_title ON keystone (title);

CREATE TABLE lantern (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_lantern_title ON lantern (title);

CREATE TABLE meadow (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_meadow_title ON meadow (title);

CREATE TABLE nexus (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_nexus_title ON nexus (title);

CREATE TABLE orchard (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_orchard_title ON orchard (title);

CREATE TABLE pavilion (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_pavilion_title ON pavilion (title);

CREATE TABLE quarry (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_quarry_title ON quarry (title);

CREATE TABLE rivulet (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_rivulet_title ON rivulet (title);

CREATE TABLE signal_post (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_signal_post_title ON signal_post (title);

CREATE TABLE terrace (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_terrace_title ON terrace (title);

CREATE TABLE uplink (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_uplink_title ON uplink (title);

CREATE TABLE vessel (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_vessel_title ON vessel (title);

CREATE TABLE waypoint (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_waypoint_title ON waypoint (title);

CREATE TABLE yearbook (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_yearbook_title ON yearbook (title);

CREATE TABLE zenith (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_zenith_title ON zenith (title);

CREATE TABLE alcove (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_alcove_title ON alcove (title);

CREATE TABLE bastion (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_bastion_title ON bastion (title);

CREATE TABLE cairn (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_cairn_title ON cairn (title);

CREATE TABLE drift (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_drift_title ON drift (title);

CREATE TABLE estuary (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_estuary_title ON estuary (title);

CREATE TABLE foundry (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_foundry_title ON foundry (title);

CREATE TABLE gallery (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_gallery_title ON gallery (title);

CREATE TABLE horizon (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_horizon_title ON horizon (title);

CREATE TABLE inlet (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_inlet_title ON inlet (title);

CREATE TABLE journey (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_journey_title ON journey (title);

CREATE TABLE kiosk (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_kiosk_title ON kiosk (title);

CREATE TABLE lookout (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_lookout_title ON lookout (title);

CREATE TABLE mosaic (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_mosaic_title ON mosaic (title);

CREATE TABLE notion (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_notion_title ON notion (title);

CREATE TABLE outpost (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_outpost_title ON outpost (title);

CREATE TABLE pier (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_pier_title ON pier (title);

CREATE TABLE quiver (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_quiver_title ON quiver (title);

CREATE TABLE roost (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_roost_title ON roost (title);

CREATE TABLE summit (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_summit_title ON summit (title);

CREATE TABLE thicket (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_thicket_title ON thicket (title);

CREATE TABLE union_hall (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_union_hall_title ON union_hall (title);

CREATE TABLE veranda (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_veranda_title ON veranda (title);

CREATE TABLE workshop (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_workshop_title ON workshop (title);

CREATE TABLE yonder (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_yonder_title ON yonder (title);

CREATE TABLE zephyr (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (area_code, series_no)
);
CREATE INDEX ix_zephyr_title ON zephyr (title);

CREATE TABLE multi_column_index_probe (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX ix_multi_column_index_probe_recorded_at_title_amount ON multi_column_index_probe (recorded_at, title, amount);

CREATE TABLE multi_index_probe (
  id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  serial_code VARCHAR(40) NOT NULL,
  batch_code VARCHAR(40) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_multi_index_probe_batch_code UNIQUE (batch_code)
);
CREATE INDEX ix_multi_index_probe_title ON multi_index_probe (title);
CREATE UNIQUE INDEX ux_multi_index_probe_serial_code ON multi_index_probe (serial_code);

CREATE TABLE wide_composite_key_probe (
  area_code VARCHAR(12) NOT NULL,
  series_no INTEGER NOT NULL,
  title VARCHAR(160) NOT NULL,
  note TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  active BOOLEAN NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  gauge_001 INTEGER,
  gauge_002 BIGINT,
  gauge_003 DECIMAL(12, 2) NOT NULL,
  gauge_004 TEXT,
  gauge_005 INTEGER,
  gauge_006 BIGINT NOT NULL,
  gauge_007 DECIMAL(12, 2),
  gauge_008 TEXT,
  gauge_009 INTEGER NOT NULL,
  gauge_010 BIGINT,
  gauge_011 DECIMAL(12, 2),
  gauge_012 TEXT NOT NULL,
  gauge_013 INTEGER,
  gauge_014 BIGINT,
  gauge_015 DECIMAL(12, 2) NOT NULL,
  gauge_016 TEXT,
  gauge_017 INTEGER,
  gauge_018 BIGINT NOT NULL,
  gauge_019 DECIMAL(12, 2),
  gauge_020 TEXT,
  gauge_021 INTEGER NOT NULL,
  gauge_022 BIGINT,
  gauge_023 DECIMAL(12, 2),
  gauge_024 TEXT NOT NULL,
  gauge_025 INTEGER,
  gauge_026 BIGINT,
  gauge_027 DECIMAL(12, 2) NOT NULL,
  gauge_028 TEXT,
  gauge_029 INTEGER,
  gauge_030 BIGINT NOT NULL,
  gauge_031 DECIMAL(12, 2),
  gauge_032 TEXT,
  gauge_033 INTEGER NOT NULL,
  gauge_034 BIGINT,
  gauge_035 DECIMAL(12, 2),
  gauge_036 TEXT NOT NULL,
  gauge_037 INTEGER,
  gauge_038 BIGINT,
  gauge_039 DECIMAL(12, 2) NOT NULL,
  gauge_040 TEXT,
  gauge_041 INTEGER,
  gauge_042 BIGINT NOT NULL,
  gauge_043 DECIMAL(12, 2),
  gauge_044 TEXT,
  gauge_045 INTEGER NOT NULL,
  gauge_046 BIGINT,
  gauge_047 DECIMAL(12, 2),
  gauge_048 TEXT NOT NULL,
  gauge_049 INTEGER,
  gauge_050 BIGINT,
  gauge_051 DECIMAL(12, 2) NOT NULL,
  gauge_052 TEXT,
  gauge_053 INTEGER,
  gauge_054 BIGINT NOT NULL,
  gauge_055 DECIMAL(12, 2),
  gauge_056 TEXT,
  gauge_057 INTEGER NOT NULL,
  gauge_058 BIGINT,
  gauge_059 DECIMAL(12, 2),
  gauge_060 TEXT NOT NULL,
  gauge_061 INTEGER,
  gauge_062 BIGINT,
  gauge_063 DECIMAL(12, 2) NOT NULL,
  gauge_064 TEXT,
  gauge_065 INTEGER,
  gauge_066 BIGINT NOT NULL,
  gauge_067 DECIMAL(12, 2),
  gauge_068 TEXT,
  gauge_069 INTEGER NOT NULL,
  gauge_070 BIGINT,
  gauge_071 DECIMAL(12, 2),
  gauge_072 TEXT NOT NULL,
  gauge_073 INTEGER,
  gauge_074 BIGINT,
  gauge_075 DECIMAL(12, 2) NOT NULL,
  gauge_076 TEXT,
  gauge_077 INTEGER,
  gauge_078 BIGINT NOT NULL,
  gauge_079 DECIMAL(12, 2),
  gauge_080 TEXT,
  gauge_081 INTEGER NOT NULL,
  gauge_082 BIGINT,
  gauge_083 DECIMAL(12, 2),
  gauge_084 TEXT NOT NULL,
  gauge_085 INTEGER,
  gauge_086 BIGINT,
  gauge_087 DECIMAL(12, 2) NOT NULL,
  gauge_088 TEXT,
  gauge_089 INTEGER,
  gauge_090 BIGINT NOT NULL,
  gauge_091 DECIMAL(12, 2),
  gauge_092 TEXT,
  gauge_093 INTEGER NOT NULL,
  gauge_094 BIGINT,
  gauge_095 DECIMAL(12, 2),
  gauge_096 TEXT NOT NULL,
  gauge_097 INTEGER,
  gauge_098 BIGINT,
  gauge_099 DECIMAL(12, 2) NOT NULL,
  gauge_100 TEXT,
  gauge_101 INTEGER,
  gauge_102 BIGINT NOT NULL,
  gauge_103 DECIMAL(12, 2),
  gauge_104 TEXT,
  gauge_105 INTEGER NOT NULL,
  gauge_106 BIGINT,
  gauge_107 DECIMAL(12, 2),
  gauge_108 TEXT NOT NULL,
  gauge_109 INTEGER,
  gauge_110 BIGINT,
  gauge_111 DECIMAL(12, 2) NOT NULL,
  gauge_112 TEXT,
  gauge_113 INTEGER,
  gauge_114 BIGINT NOT NULL,
  gauge_115 DECIMAL(12, 2),
  gauge_116 TEXT,
  gauge_117 INTEGER NOT NULL,
  gauge_118 BIGINT,
  gauge_119 DECIMAL(12, 2),
  gauge_120 TEXT NOT NULL,
  gauge_121 INTEGER,
  gauge_122 BIGINT,
  gauge_123 DECIMAL(12, 2) NOT NULL,
  gauge_124 TEXT,
  gauge_125 INTEGER,
  gauge_126 BIGINT NOT NULL,
  gauge_127 DECIMAL(12, 2),
  gauge_128 TEXT,
  gauge_129 INTEGER NOT NULL,
  gauge_130 BIGINT,
  gauge_131 DECIMAL(12, 2),
  gauge_132 TEXT NOT NULL,
  gauge_133 INTEGER,
  gauge_134 BIGINT,
  gauge_135 DECIMAL(12, 2) NOT NULL,
  gauge_136 TEXT,
  gauge_137 INTEGER,
  gauge_138 BIGINT NOT NULL,
  gauge_139 DECIMAL(12, 2),
  gauge_140 TEXT,
  gauge_141 INTEGER NOT NULL,
  gauge_142 BIGINT,
  gauge_143 DECIMAL(12, 2),
  gauge_144 TEXT NOT NULL,
  gauge_145 INTEGER,
  gauge_146 BIGINT,
  gauge_147 DECIMAL(12, 2) NOT NULL,
  gauge_148 TEXT,
  gauge_149 INTEGER,
  gauge_150 BIGINT NOT NULL,
  gauge_151 DECIMAL(12, 2),
  gauge_152 TEXT,
  gauge_153 INTEGER NOT NULL,
  gauge_154 BIGINT,
  gauge_155 DECIMAL(12, 2),
  gauge_156 TEXT NOT NULL,
  gauge_157 INTEGER,
  gauge_158 BIGINT,
  gauge_159 DECIMAL(12, 2) NOT NULL,
  gauge_160 TEXT,
  gauge_161 INTEGER,
  gauge_162 BIGINT NOT NULL,
  gauge_163 DECIMAL(12, 2),
  gauge_164 TEXT,
  gauge_165 INTEGER NOT NULL,
  gauge_166 BIGINT,
  gauge_167 DECIMAL(12, 2),
  gauge_168 TEXT NOT NULL,
  gauge_169 INTEGER,
  gauge_170 BIGINT,
  gauge_171 DECIMAL(12, 2) NOT NULL,
  gauge_172 TEXT,
  gauge_173 INTEGER,
  gauge_174 BIGINT NOT NULL,
  gauge_175 DECIMAL(12, 2),
  gauge_176 TEXT,
  gauge_177 INTEGER NOT NULL,
  gauge_178 BIGINT,
  gauge_179 DECIMAL(12, 2),
  gauge_180 TEXT NOT NULL,
  gauge_181 INTEGER,
  gauge_182 BIGINT,
  gauge_183 DECIMAL(12, 2) NOT NULL,
  gauge_184 TEXT,
  gauge_185 INTEGER,
  gauge_186 BIGINT NOT NULL,
  gauge_187 DECIMAL(12, 2),
  gauge_188 TEXT,
  gauge_189 INTEGER NOT NULL,
  gauge_190 BIGINT,
  gauge_191 DECIMAL(12, 2),
  gauge_192 TEXT NOT NULL,
  gauge_193 INTEGER,
  gauge_194 BIGINT,
  gauge_195 DECIMAL(12, 2) NOT NULL,
  gauge_196 TEXT,
  gauge_197 INTEGER,
  gauge_198 BIGINT NOT NULL,
  gauge_199 DECIMAL(12, 2),
  gauge_200 TEXT,
  gauge_201 INTEGER NOT NULL,
  gauge_202 BIGINT,
  gauge_203 DECIMAL(12, 2),
  gauge_204 TEXT NOT NULL,
  gauge_205 INTEGER,
  gauge_206 BIGINT,
  gauge_207 DECIMAL(12, 2) NOT NULL,
  gauge_208 TEXT,
  gauge_209 INTEGER,
  gauge_210 BIGINT NOT NULL,
  gauge_211 DECIMAL(12, 2),
  gauge_212 TEXT,
  gauge_213 INTEGER NOT NULL,
  gauge_214 BIGINT,
  gauge_215 DECIMAL(12, 2),
  gauge_216 TEXT NOT NULL,
  gauge_217 INTEGER,
  gauge_218 BIGINT,
  gauge_219 DECIMAL(12, 2) NOT NULL,
  gauge_220 TEXT,
  gauge_221 INTEGER,
  gauge_222 BIGINT NOT NULL,
  gauge_223 DECIMAL(12, 2),
  gauge_224 TEXT,
  gauge_225 INTEGER NOT NULL,
  gauge_226 BIGINT,
  gauge_227 DECIMAL(12, 2),
  gauge_228 TEXT NOT NULL,
  gauge_229 INTEGER,
  gauge_230 BIGINT,
  gauge_231 DECIMAL(12, 2) NOT NULL,
  gauge_232 TEXT,
  gauge_233 INTEGER,
  gauge_234 BIGINT NOT NULL,
  gauge_235 DECIMAL(12, 2),
  gauge_236 TEXT,
  gauge_237 INTEGER NOT NULL,
  gauge_238 BIGINT,
  gauge_239 DECIMAL(12, 2),
  gauge_240 TEXT NOT NULL,
  gauge_241 INTEGER,
  gauge_242 BIGINT,
  gauge_243 DECIMAL(12, 2) NOT NULL,
  gauge_244 TEXT,
  gauge_245 INTEGER,
  gauge_246 BIGINT NOT NULL,
  gauge_247 DECIMAL(12, 2),
  gauge_248 TEXT,
  gauge_249 INTEGER NOT NULL,
  gauge_250 BIGINT,
  PRIMARY KEY (series_no, area_code)
);
CREATE INDEX ix_wide_composite_key_probe_title ON wide_composite_key_probe (title);

