// wide-schema regenerates the checked-in catalog-navigation fixtures.
//
// Run from the repository root:
//
//	go run ./tools/wide-schema
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const wideTable = "archive"

var tableNames = []string{
	"archive", "beacon", "canvas", "docket", "ember", "folio", "grotto", "harvest", "island", "juncture",
	"keystone", "lantern", "meadow", "nexus", "orchard", "pavilion", "quarry", "rivulet", "signal_post", "terrace",
	"uplink", "vessel", "waypoint", "yearbook", "zenith", "alcove", "bastion", "cairn", "drift", "estuary",
	"foundry", "gallery", "horizon", "inlet", "journey", "kiosk", "lookout", "mosaic", "notion", "outpost",
	"pier", "quiver", "roost", "summit", "thicket", "union_hall", "veranda", "workshop", "yonder", "zephyr",
}

func main() {
	files := map[string]string{
		filepath.Join("deploy", "postgres-init", "03-wide-schema.sql"): renderPostgreSQL(),
		filepath.Join("deploy", "mysql-init", "03-wide-schema.sql"):    renderMySQL(),
	}
	for path, contents := range files {
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
			os.Exit(1)
		}
	}
}

func header(engine string) string {
	return "-- Generated by tools/wide-schema for " + engine + ". DO NOT EDIT.\n" +
		"-- Regenerate from the repository root with: go run ./tools/wide-schema\n" +
		"--\n" +
		"-- This is schema only: it deliberately contains no rows or foreign keys. Its\n" +
		"-- size is what makes catalog navigation real rather than a one-object happy path,\n" +
		"-- but the fixture must still be safe for every test that shares these databases.\n" +
		"--\n" +
		"-- The 256-column archive table is deliberately in the second schema each engine\n" +
		"-- exposes: harbor follows atelier in PostgreSQL, and ledger follows MySQL's\n" +
		"-- testbed database. A resolver that reads only the first schema would\n" +
		"-- otherwise find enough ordinary tables to look healthy while never reaching the\n" +
		"-- wide-table path this fixture is here to exercise.\n" +
		"--\n" +
		"-- The shapes are consequently not symmetric. PostgreSQL schemas are namespaces\n" +
		"-- inside testbed, while a MySQL schema is a database; more than one schema there\n" +
		"-- must be testbed and ledger, not two names nested in testbed. Keeping that\n" +
		"-- distinction visible prevents a cross-engine abstraction from hiding it.\n" +
		"--\n" +
		"-- PostgreSQL's init connection is its image superuser, so SET ROLE cerberus below\n" +
		"-- is load-bearing rather than cosmetic. Without it that superuser owns the named\n" +
		"-- schemas and their tables, while the test login merely connects and cannot read\n" +
		"-- the fixture; creating them as cerberus makes its ownership the permission grant.\n\n"
}

func renderPostgreSQL() string {
	var b strings.Builder
	b.WriteString(header("PostgreSQL"))
	b.WriteString("\\connect testbed\n\n")
	b.WriteString("-- The test login owns these objects, so the executor can read them.\n")
	b.WriteString("SET ROLE cerberus;\n\n")
	for _, schema := range []string{"atelier", "harbor"} {
		fmt.Fprintf(&b, "CREATE SCHEMA %s;\n\n", schema)
		for i, table := range tableNames {
			writePostgreSQLTable(&b, schema, table, i, schema == "harbor" && table == wideTable)
		}
	}
	return b.String()
}

func writePostgreSQLTable(b *strings.Builder, schema, table string, ordinal int, wide bool) {
	qualified := schema + "." + table
	fmt.Fprintf(b, "CREATE TABLE %s (\n", qualified)
	if wide {
		writePostgreSQLWideColumns(b)
		b.WriteString("  PRIMARY KEY (id)\n")
	} else if ordinal%2 == 0 {
		b.WriteString("  id BIGINT NOT NULL,\n")
		writePostgreSQLSharedColumns(b)
		b.WriteString("  PRIMARY KEY (id)\n")
	} else {
		b.WriteString("  area_code VARCHAR(12) NOT NULL,\n")
		b.WriteString("  series_no INTEGER NOT NULL,\n")
		writePostgreSQLSharedColumns(b)
		b.WriteString("  PRIMARY KEY (area_code, series_no)\n")
	}
	b.WriteString(");\n")
	fmt.Fprintf(b, "CREATE INDEX ix_%s_title ON %s (title);\n\n", table, qualified)
}

func writePostgreSQLSharedColumns(b *strings.Builder) {
	b.WriteString("  title VARCHAR(160) NOT NULL,\n")
	b.WriteString("  note TEXT,\n")
	b.WriteString("  amount NUMERIC(12, 2) NOT NULL,\n")
	b.WriteString("  active BOOLEAN NOT NULL,\n")
	b.WriteString("  recorded_at TIMESTAMPTZ NOT NULL,\n")
}

func writePostgreSQLWideColumns(b *strings.Builder) {
	b.WriteString("  id BIGINT NOT NULL,\n")
	writePostgreSQLSharedColumns(b)
	for i := 1; i <= 250; i++ {
		fmt.Fprintf(b, "  measure_%03d %s%s,\n", i, postgreSQLMeasureType(i), nullableSuffix(i))
	}
}

func postgreSQLMeasureType(i int) string {
	return []string{"INTEGER", "BIGINT", "NUMERIC(12, 2)", "TEXT"}[(i-1)%4]
}

func nullableSuffix(i int) string {
	if i%3 == 0 {
		return " NOT NULL"
	}
	return ""
}

func renderMySQL() string {
	var b strings.Builder
	b.WriteString(header("MySQL"))
	for _, database := range []string{"testbed", "ledger"} {
		fmt.Fprintf(&b, "USE %s;\n\n", database)
		for i, table := range tableNames {
			writeMySQLTable(&b, table, i, database == "ledger" && table == wideTable)
		}
	}
	return b.String()
}

func writeMySQLTable(b *strings.Builder, table string, ordinal int, wide bool) {
	fmt.Fprintf(b, "CREATE TABLE %s (\n", table)
	if wide {
		writeMySQLWideColumns(b)
		b.WriteString("  PRIMARY KEY (id)\n")
	} else if ordinal%2 == 0 {
		b.WriteString("  id BIGINT NOT NULL,\n")
		writeMySQLSharedColumns(b)
		b.WriteString("  PRIMARY KEY (id)\n")
	} else {
		b.WriteString("  area_code VARCHAR(12) NOT NULL,\n")
		b.WriteString("  series_no INTEGER NOT NULL,\n")
		writeMySQLSharedColumns(b)
		b.WriteString("  PRIMARY KEY (area_code, series_no)\n")
	}
	b.WriteString(");\n")
	fmt.Fprintf(b, "CREATE INDEX ix_%s_title ON %s (title);\n\n", table, table)
}

func writeMySQLSharedColumns(b *strings.Builder) {
	b.WriteString("  title VARCHAR(160) NOT NULL,\n")
	b.WriteString("  note TEXT,\n")
	b.WriteString("  amount DECIMAL(12, 2) NOT NULL,\n")
	b.WriteString("  active BOOLEAN NOT NULL,\n")
	b.WriteString("  recorded_at TIMESTAMP NOT NULL,\n")
}

func writeMySQLWideColumns(b *strings.Builder) {
	b.WriteString("  id BIGINT NOT NULL,\n")
	writeMySQLSharedColumns(b)
	for i := 1; i <= 250; i++ {
		fmt.Fprintf(b, "  measure_%03d %s%s,\n", i, mySQLMeasureType(i), nullableSuffix(i))
	}
}

func mySQLMeasureType(i int) string {
	return []string{"INTEGER", "BIGINT", "DECIMAL(12, 2)", "TEXT"}[(i-1)%4]
}
